let renderer = ColdSVG.createSVGRenderer.inDocument(800,800)
let square = ColdSVG.rectangle(80, 80, 'red').setParent(renderer)
let line = ColdSVG.line(0,0,400,400,5,'blue').setParent(renderer)
let circle = ColdSVG.circle(45,'pink').setParent(renderer)
let elipse = ColdSVG.elipse(10,100,'green').setParent(renderer)
let image = ColdSVG.image('https://avatars2.githubusercontent.com/u/9648865?v=3&s=460').setParent(renderer)
let poligon = ColdSVG.poligon().setParent(renderer)
let polyline = ColdSVG.polyline().setParent(renderer)
let text = ColdSVG.text('SVG Text').setParent(renderer)
let path = ColdSVG.path().setParent(renderer)
let path2 = ColdSVG.path()
renderer.addDefinition(path2,'text')
let textPath = ColdSVG.textPath('asd','text').setParent(renderer)